name: Upload ROM

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  compile-and-upload:
    name: Compile and Upload
    runs-on: windows-latest
    
    steps:
      - name: Checkout SGDK
        uses: actions/checkout@v2
        with:
          repository: Stephane-D/SGDK.git
          path: SGDK
          ref: v1.65

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: repo
          lfs: true
      
      - name: Compile ROM
        working-directory: repo
        shell: cmd
        env:
          GDK_WIN: ${{ github.workspace }}\SGDK
        run: |
          %GDK_WIN%\bin\make -f %GDK_WIN%\makefile.gen
      
      - name: Generate Timestamp
        shell: bash
        run: echo TIMESTAMP=$(date +%s) >> $GITHUB_ENV
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ env.TIMESTAMP }}
          path: ./repo/out/
          if-no-files-found: error